name = "CrayonCraft"
author = "The Crayons"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f53c5e003ec3e4b108c9506612ca3b9ef8305b29ee0487e6e6852a3321fb8a5"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
