name = "CrayonCraft"
author = "The Quilt BIPoC Community"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74030bb2c627e791b69804d2ed584359a18c104e99ffd3ff056bd18934a388d1"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
