name = "CrayonCraft"
author = "The Crayons"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49d4c8f704ae848fd6121bec3f90e0a73f44c47c1c6b06f44117814fcfa36999"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
