name = "CrayonCraft"
author = "The Quilt BIPoC Community"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08482db384ce1de9477db62d2e3636007d3c4a9af1c9ebc0ebd7895eb929cb9"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
